apiVersion: skaffold/v3
kind: Config
metadata:
  name: vanity
build:
  artifacts:
    - image: us-central1-docker.pkg.dev/com-seankhliao/run/vanity
      ko:
        fromImage: cgr.dev/chainguard/static@sha256:67a1b00e0134e2b3a614c7198a26f7deed9d11b7acad4d52c79c0cfd47a2eae7
        env:
          - CGO_ENABLED=0
        flags:
          - -trimpath
        ldflags:
          - -s
          - -w
        dependencies:
          paths:
            - "**/*.go"
            - "go.mod"
  tagPolicy:
    inputDigest: {}
  platforms:
    - linux/amd64
manifests:
  rawYaml:
    - deploy/cloudrun/service.yaml
deploy:
  cloudrun:
    region: us-central1
